version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Running Pre Build
  build:
    commands:
      - echo Build started on `date`
      - mvn clean test -Dkarate.options="-t @${TAG}" -Dkarate.targetEnv="${ENV}"
      - mv target targetMain
      - mvn clean test -Dkarate.options="-t @DeleteTestAssets" -Dkarate.targetEnv="${ENV}"
      - mv target targetDelete
      - mv targetMain target
    cache:
      paths:
        - '/root/.m2/**/*'
  post_build:
    commands:
      - echo Build completed on `date`
      - cd $CODEBUILD_SRC_DIR/target/*
      - echo Listing the contents of Html Reports
      - ls -al
reports:
  CucsReports:
    files:
      - '**/*'
    base-directory: 'target/cucumber-html-reports/'
artifacts:
  secondary-artifacts:
    test_automation_output:
      files:
        #- $CODEBUILD_SRC_DIR/target/cucumber-html-reports/**/*
        - target/**/*
cache:
  paths:
    - '/root/.m2/**/*'